[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# For SPAs and Next.js applications to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs" 